FLASK_APP="app"
FLASK_ENV="development"
FLASK_CONFIG="development"
FLASK_RUN_HOST="127.0.0.1"
FLASK_RUN_PORT=5000

FLASK_DATABASE_USER="remote"
FLASK_DATABASE_PASSWORD="zylT#1013"
FLASK_DATABASE_HOST="47.97.109.179"
FLASK_DATABASE_NAME="lanting_test"

FLASK_SECRET_KEY="dhka$%^gda675#%$$%rFgfsagGGAAFE"

MAIL_USERNAME="lantingxuapplet@163.com"
MAIL_PASSWORD="tang1013"
